In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3219, 6822, 518, 1967],
 [3219, 6822, 518, 2730],
 [3219, 209, 518, 5440],
 [3963, 7337, 8431, 3179, 5985],
 [3963, 7337, 8431, 3179, 3187],
 [3643, 3219, 8825, 518, 9318],
 [4613, 1300, 4705, 3179]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3219 6822  518 1967]
 [   0    0    0    0 3219 6822  518 2730]
 [   0    0    0    0 3219  209  518 5440]
 [   0    0    0 3963 7337 8431 3179 5985]
 [   0    0    0 3963 7337 8431 3179 3187]
 [   0    0    0 3643 3219 8825  518 9318]
 [   0    0    0    0 4613 1300 4705 3179]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\itian\python\ml-customer-retention\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 284ms/step


array([[[ 9.09669325e-03, -3.58269364e-03,  6.67985529e-03,
         -3.55936661e-02,  3.18146609e-02,  2.73786895e-02,
         -4.31043617e-02, -3.25590596e-02,  3.38653214e-02,
         -3.01570818e-03],
        [ 9.09669325e-03, -3.58269364e-03,  6.67985529e-03,
         -3.55936661e-02,  3.18146609e-02,  2.73786895e-02,
         -4.31043617e-02, -3.25590596e-02,  3.38653214e-02,
         -3.01570818e-03],
        [ 9.09669325e-03, -3.58269364e-03,  6.67985529e-03,
         -3.55936661e-02,  3.18146609e-02,  2.73786895e-02,
         -4.31043617e-02, -3.25590596e-02,  3.38653214e-02,
         -3.01570818e-03],
        [ 9.09669325e-03, -3.58269364e-03,  6.67985529e-03,
         -3.55936661e-02,  3.18146609e-02,  2.73786895e-02,
         -4.31043617e-02, -3.25590596e-02,  3.38653214e-02,
         -3.01570818e-03],
        [-2.55081896e-02,  4.68034483e-02, -3.36350575e-02,
         -3.46849337e-02,  1.82058699e-02,  4.43726815e-02,
          3.16472910e-02, -1.08553544e-02, -3.237543

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 3219, 6822,  518, 1967], dtype=int32)

In [15]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None